#ifndef UPGRADEMGR_SERVICE_LIB_GLOBAL_DEFS_H
#define UPGRADEMGR_SERVICE_LIB_GLOBAL_DEFS_H

#include <qglobal.h>

#ifdef UMM_SERVICE_STATIC_LIB
   #define UMM_SERVICE_LIB_EXPORT 
#else
   #ifdef UMM_SERVICE_LIBRARY
      #define UMM_SERVICE_LIB_EXPORT Q_DECL_EXPORT
   #else
      #define UMM_SERVICE_LIB_EXPORT Q_DECL_IMPORT
   #endif
#endif

#endif // UPGRADEMGR_SERVICE_LIB_GLOBAL_DEFS_H
