#ifndef UPGRADEMGR_MASTER_LIB_GLOBAL_ERROR_CODE_H
#define UPGRADEMGR_MASTER_LIB_GLOBAL_ERROR_CODE_H

namespace ummlib{

const int E_PROTOCOL_ILL_FORMAT = 1;

}//ummlib

#endif // UPGRADEMGR_MASTER_LIB_GLOBAL_ERROR_CODE_H

